# Generated by Django 4.0.1 on 2022-01-28 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='sumarry',
            new_name='summary',
        ),
    ]
